services:
  - type: web
    name: sports-dunia
    env: static
    buildCommand: node build.js
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 16.20.2
    headers:
      - path: /**
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /
        name: X-Frame-Options
        value: DENY
